jellyfin:  
  image:
    repository: jellyfin/jellyfin
    tag: 10.8.1
    pullPolicy: IfNotPresent
  
  # -- environment variables. See [image docs](https://jellyfin.org/docs/general/administration/configuration.html) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Denver
  
  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      enabled: true
      type: LoadBalancer
      ports:
        http:
          port: 80
          targetPort: 8096
  
  ingress:
    main:
      enabled: false
  
  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: nfs-client
      mountPath: /config
  
    # Cache does NOT contain temporary transcoding data.
    cache:
      enabled: false
      mountPath: /cache
  
    media:
      enabled: false
      mountPath: /media
  
  # -- Configure the Security Context for the Pod
  podSecurityContext: {}
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568
  #   # Hardware acceleration using an Intel iGPU w/ QuickSync
  #   # These IDs below should be matched to your `video` and `render` group on the host
  #   # To obtain those IDs run the following grep statement on the host:
  #   # $ cat /etc/group | grep "video\|render"
  #   # video:x:44:
  #   # render:x:109:
  #   supplementalGroups:
  #   - 44
  #   - 109
  
  # resources:
  #   requests:
  #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
  #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
  #     gpu.intel.com/i915: 1
  #     cpu: 200m
  #     memory: 256Mi
  #   limits:
  #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
  #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
  #     gpu.intel.com/i915: 1
  #     memory: 4096Mi
