apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: default
  source:
    path: charts/metallb
    repoURL: https://github.com/heywoodlh/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
