apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: spodcast-php
  name: spodcast-php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spodcast-php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: spodcast-php
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101 
      containers:
        - image: php:7-fpm
          name: php
          resources: {}
          volumeMounts:
            - mountPath: /spodcast
              name: spodcast-data
      restartPolicy: Always
      volumes:
        - name: spodcast-data 
          persistentVolumeClaim:
            claimName: spodcast-data 
status: {}
