---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spodcast-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spodcast
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spodcast
            image: heywoodlh/spodcast:0.5.0
            imagePullPolicy: Always
            command:
            - spodcast
            - -c 
            - /data/spodcast.json 
            - --log-level 
            - info 
            - "--transcode"
            - "yes"
            - --max-episodes
            - "10"
            - "https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk"
            - "&&"
            - chown -R 101:101 /data/html
            volumeMounts:
            - name: spodcast-data
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: spodcast-data 
            persistentVolumeClaim:
              claimName: spodcast-data

