---
apiVersion: v1
kind: Pod
metadata:
  name: heywoodlh-test-pod 
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "ls", "/data" ]
      volumeMounts:
      - name: test-volume
        mountPath: /data
  nodeSelector:
    kubernetes.io/hostname: node-2
  restartPolicy: Never
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: "spodcast-data"
