argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.1.6
  nodeSelector: 
    kubernetes.io/hostname: master
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    service:
      type: LoadBalancer
      loadBalancerIP: "10.0.60.10"
