---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gotify-data 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  storageClassName: nfs-client
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gotify-config 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: nfs-client
status: {}

