apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydroxide.fullname" . }}
  labels:
    {{- include "hydroxide.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.imap.port }}
      targetPort: 1143
      protocol: TCP
      name: imap
    - port: {{ .Values.service.smtp.port }}
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port:  {{ .Values.service.carddav.port }}
      targetPort: 8080
      protocol: TCP
      name: carddav
  selector:
    {{- include "hydroxide.selectorLabels" . | nindent 4 }}
