apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gotify-convert-ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
status: {}
